trigger:
  branches:
    include:
      - master  # Ou qualquer branch que você queira monitorar.

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build --configuration Release
  displayName: 'Build Solution'

#- script: |
#    git config --global pull.rebase false
#    git pull https://$(AZUREDEVOPS)@dev.azure.com/anthonydsant/_git/FinTracker
#  displayName: 'Sync to Azure DevOps'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host ' reflect Azure Devops repo changes to GitHub repo'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '
      $stageDir = '$(Build.SourcesDirectory)' | Split-Path
      $githubDir = $stageDir +"\"+"gitHub"
      $destination = $githubDir +"\"+"FinTracker.git"
      #please provide your username
      $alias = 'anthonyhw:'+ "$(Github.PAT)"
      #Please make sure, you remove https from azure-repo-clone-url
      $sourceURL = 'https://$(AzureDevOps.PAT)@dev.azure.com/anthonydsant/_git/FinTracker'
      #Please make sure, you remove https from github-repo-clone-url
      $destURL = 'https://' + $alias + '@github.com/Anthonyhw/FinTracker/'
      #Check if the parent directory exists and delete
      if((Test-Path -path $githubDir))
      {
        Remove-Item -Path $githubDir -Recurse -force
      }
      if(!(Test-Path -path $githubDir))
      {
        New-Item -ItemType directory -Path $githubDir
        Set-Location $githubDir
        git clone --mirror $sourceURL
      }
      else
      {
        Write-Host "The given folder path $githubDir already exists";
      }
      Set-Location $destination
      Write-Output '*****Git removing remote secondary****'
      git remote rm master
      Write-Output '*****Git remote add****'
      git remote add --mirror=fetch master $destURL
      Write-Output '*****Git fetch origin****'
      git fetch $sourceURL
      Write-Output '*****Git push secondary****'
      git push master --all
      Write-Output '**Azure Devops repo synced with Github repo**'
      Set-Location $stageDir
      if((Test-Path -path $githubDir))
      {
       Remove-Item -Path $githubDir -Recurse -force
      }