trigger:
  branches:
    include:
      - master  # Ou qualquer branch que você queira monitorar.

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet build --configuration Release
  displayName: 'Build Solution'

- script: |
    git push https://$(AZUREDEVOPS)@dev.azure.com/anthonydsant/_git/FinTracker main
  displayName: 'Sync to Azure DevOps'